
name: Changelog
on:
  push:
    tags: ["v*.*.*"]
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate minimal changelog
        run: echo "$GITHUB_REF_NAME" > CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update changelog"
